const express = require('express')
const passport = require('../config/passport')
const auth = require('./modules/auth')
const { apiErrorHandler } = require('../middleware/error-handler')
const router = express.Router()
const users = require('./modules/users')
const friendships = require('./modules/friendships')
const books = require('./modules/books')
const events = require('./modules/events')
const reviews = require('./modules/reviews')
const sockets = require('./modules/sockets')
const { authenticated } = require('../middleware/auth')
const userController = require('../controllers/user-controller')

// routes
router.post('/api/v1/users/login', passport.authenticate('local', { session: false }), userController.logIn)
router.post('/api/v1/users', userController.signUp)
router.get('/api/v1/get_current_user', authenticated, userController.getCurrentUser)
router.use('/api/v1/users', authenticated, users)
router.use('/api/v1/friendships', authenticated, friendships)
router.use('/api/v1/books', authenticated, books)
router.use('/api/v1/events', authenticated, events)
router.use('/api/v1/reviews', authenticated, reviews)
router.use('/api/v1/sockets', authenticated, sockets)
router.use('/api/v1', apiErrorHandler)
router.use('/', auth)

module.exports = router